# Generated by Django 4.0 on 2021-12-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('relation', models.CharField(max_length=30)),
                ('gift_rating', models.FloatField()),
                ('giftimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
